<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Advik99" failures="1" tests="8" name="com.employeeapi.testcase.TC_001_GET_ALL_EMP" time="0.033" errors="0" timestamp="2021-10-18T07:03:25 EDT" skipped="0">
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationCode" time="0.003">
    <failure message="--&gt;FAIL&lt;-- statusCodeAcutal 200 expected [201] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: -->FAIL<-- statusCodeAcutal 200 expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.employeeapi.testcase.Validation.validationStatusCode(Validation.java:38)
at com.employeeapi.testcase.TC_001_GET_ALL_EMP.validationCode(TC_001_GET_ALL_EMP.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validationCode -->
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationLength" time="0.001"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationTime" time="0.003"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationServer" time="0.002"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationBody" time="0.018"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationEncoding" time="0.002"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationContent" time="0.002"/>
  <system-out/>
  <testcase classname="com.employeeapi.testcase.TC_001_GET_ALL_EMP" name="validationLine" time="0.002"/>
  <system-out/>
</testsuite> <!-- com.employeeapi.testcase.TC_001_GET_ALL_EMP -->
